### ISSUE TITLE
About HO-3D / FPHA measure.

### ISSUE THREAD

**Issue by chanwo0kim** [korrawe/grasping_field_demo#7]
Hello!

I'm very interested in your test results and I'm trying to implement it.

However, I am having some difficulties and I have a question!

How did you handle data in HO-3D or FPHA in the point cloud setting?

More specifically, I know I need to pass the model after moving the HO-3D or FPHA into obman object space, how did you do this?

I will be waiting for your or any others reply.

Thank you! :)

**Comment by korrawe** [comment]
I believe you are talking about how I normalized the object location? 
I translate the object such that the hand root joint will be at the origin when it is grabbing the object (then the hand can be generated at the origin). So for HO3D and FPHA objects with ground truth hand locations, they can be translated like this

```
root_joint = hand_joint[0]  
hand_joint = hand_joint - root_joint 
hand_vertices = hand_vertices - root_joint 
object_vertices = object_vertices - root_joint
```
The model also gives better results if the octant that the object lies in matches the mean octant of the Obman object (although I cannot remember which octant it is)

Best

**Comment by chanwo0kim** [comment]
First of all, thanks for the reply!

I have an additional question for what you said.

Maybe this is the "Octant of Obman Object" you're talking about? 
**trans = np.array([-0.0793, 0.0208, -0.6924])**
If this is correct, is it correct to use the rotation matrix in ground truth, and move the object mesh(or point cloud) by adding only translation?

And at the time of testing, I saw the contents of the paper that HO-3D frames were used 66034 / 11524 (total of 77558).
Then, did you make hand meshes for all objects(**10 kinds**) in the frame and measure them?(77558 hand-object pairs)

I will be waiting for your reply.

Thank you! :)

**Comment by korrawe** [comment]
For the first question, I am not sure where the numbers come from but you can move the object by adding only the translation. The reported number is also done with only translation. I mentioned the octant in case you want to use the object trained on obman on new objects.

For generating new hands, I first sampled the object configuration from the target dataset (10 kinds x number of configurations). I believe the number of configurations is 5. For each object, I sample 10 hands. The evaluation is then done on these sampled hands (10 x 5 x 10).
